(********************************************************************
 * COPYRIGHT --  
 ********************************************************************
 * Program: PiperModuleTemplate
 * File: PiperModuleTemplateCyclic.st
 * Author: Josh
 * Created: October 03, 2013
 ********************************************************************
 * Implementation of program PiperModuleTemplate
 ********************************************************************)

PROGRAM _CYCLIC

	// Call PiperModuleInterface to interface with the rest of the machine
	PiperModuleInterface;
	
	//Put your code here

END_PROGRAM
