(********************************************************************
 * COPYRIGHT -- Automation Resources Group
 ********************************************************************
 * Program: MachineProg
 * File: MachineProgInit.st
 * Author: David Blackburn
 * Created: November 10, 2011
 ********************************************************************
 * Implementation of program MachineProg
 ********************************************************************)


PROGRAM _INIT
	
	//Hide Main page state model
	HMIMachineState.MachineStateLayer.StatusDP:=	1;

END_PROGRAM
